### ISSUE TITLE
As a registered user, I want to login to the application so that I can edit and reserve items.

### ISSUE THREAD

**Issue by dcochs3** [MagiShi/CrunchApp#8]
## Story/Task Details
- [x] Login button on landing/intro page
- [x] Input boxes for username/email and password
- [x] Button to press to log in
- [ ] Cancel login button
- [x] Forgot password button
- [x] Register button for new users
- [x] Valid and correct input takes user to home page
- [x] Invalid input notifies user (email isn't in the format of an email)
- [x] Incorrect input notifies user (your email or password is wrong)

## Acceptance Scenarios
_Scenario: The registered user enters the correct username with correct corresponding password._
- Given that the registered user is on the login page;
- When the registered user enters in a username and a password that matches the account’s set password 
and they press the login button;
- Then the registered user is logged in
and they see the lookup items page.

_Scenario: The registered user enters a username with an incorrect password._
- Given that the registered user is on the login page; 
- When the registered user enters in a username and incorrect password
and they press the login button;
- Then the registered user sees a warning message that says the password is incorrect
and they remain on the login page
and they see the previously entered username still in the username input box
and they see the password input box cleared.

_Scenario: The registered user presses the forgot password button._
- Given that the registered user is on the login page;
- When the registered user presses the forgot password button
and they enter in their username
and they press the send password by email button;
- Then the registered user receives an email with a link to reset their password.

_Scenario: The registered user decides not to login._
- Given that the registered user is on the login page;
- When the registered user presses the cancel button;
- Then the registered user is taken back to the home page.

## Done Done Criteria

**Comment by MagiShi** [comment]
The home page was currently the login page, thus making the cancel button unnecessary.

**Comment by phuynh35** [comment]
i didnt see the implementation of forgot password button in the iteration plan. Are you gonna implement it in sprint 2?

**Comment by MagiShi** [comment]
It was my understanding that during the meeting, that all email implementation was a part of future goals. However, if you wish to do the email implementation, feel free.

**Comment by MagiShi** [comment]
Also, as I am looking into this, there needs to be a "Forget Password" button (not href) on the HTML page, I cannot add any implementation without the UI part to connect to it. This will need to be added on your part before I can do anything.

**Comment by phuynh35** [comment]
why do you need it as a button? I thought it just links to another page like Sign-up or Use as Guest.

**Comment by MagiShi** [comment]
Because the user story says that a pop-up is supposed to appear, which would not occur with a link.  But I just built off the link since that's what is there. But because of this, I also had to create a new page for the email, which hopefully wasn't a repeat of anything you did (It didn't seem to be, but just wanted to check since you are doing the UI pages).  Email should be working now, please check and close issue if so.

**Comment by phuynh35** [comment]
Oh ok, sorry about that. And i think the app is down

**Comment by MagiShi** [comment]
App should be up.

**Comment by phuynh35** [comment]
Oh I was not thinking to implement it or anything right now. I saw that on the list of this issue and just add it in. Also, I didnt remember we talking about this function in meetings at all so that is why I asked. Did you have to complete this as an extra for this sprint? If that is the case, I am so sorry.

**Comment by MagiShi** [comment]
We mentioned that we were not going to have emails implemented during the meeting due to complications to security and other factors that would make proper implementation difficult.  "Forgot Password" is the same.  It is fine, but next time, please communicate your intentions clearly, so that we don't have any misunderstandings 😄
